name: Deploy to Hostinger

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Hostinger
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 145.14.152.127
          username: u767822519
          key: ${{ secrets.HOSTINGER_KEY }}
          port: 65002
          script: |
            cd /home/u767822519/domains/eazeehub.com/public_html/serlzo/wp-content/plugins/serlzo
            git pull origin main
